/** WELCOME TO AN AUTOMATED LOGIN PROGRAM THAT CAN BYPASS HCAPTCHA
 * TO USE, NEED NODE.JS, PUPPETEER, PUPPETEER-EXTRA, PUPPETEER-EXTRA-PLUGIN-STEALTH INSTALLED
 * RUN USING "Node ./main.js"
 * WILL OPEN UP BROWSER AND WITH THE GIVEN ACCESSORS SHOULD FIND AND WRITE TEXT TO THOSE FIELDS, AND THEN PRESS THE GIVEN BUTTON
 * LIKE FOR WRITING A USERNAME AND PASSWORD IN A LOGIN PAGE, AND PRESSING THE LOGIN BUTTON
 * 
 */
